### ISSUE TITLE
NoSuchMethodError: com.hawolt.yaml.SystemYaml.rewrite()

### ISSUE THREAD

**Issue by ReprimandedKaito** [Riotphobia/Netherblade#23]
The app displays a dialog that it's downloading, extracting, and finally that it is initialized.
but then an empty screen is displayed.

Tested:
- File: `Netherblade-1.401-jar-with-dependencies.jar`
- Operating system: Windows 10 x64
- JDKs:
    - Oracle JDK 8
    - OpenJDK 11
    - OpenJDK 15
    - Amazon Corretto 11
    - Amazon Corretto 15

![cmd](https://github.com/Riotphobia/Netherblade/assets/116013630/86e1bcce-5a7d-4692-a2f1-3a0195b86a0a)
![empty](https://github.com/Riotphobia/Netherblade/assets/116013630/48effb04-8a23-4516-80bf-e4f15232145a)

**Comment by hawolt** [comment]
Thanks for the response, I figured out that this is caused by two classes being called SystemYaml residing in the same package. I have renamed Netherblades SystemYaml to LocalSystemYaml in the latest commit https://github.com/Riotphobia/Netherblade/commit/dac9e6450d067720196963746044e0d860880c90
I will attach a new release without changing the version.
